# Generated by Django 5.2.12 on 2026-03-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_appointment_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to='myapp.users'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dentistry', 'General Dentistry'), ('laboratory', 'Laboratory Testing'), ('health_check', 'Health Check-Up'), ('pharmacy', 'Pharmacy'), ('general', 'General / Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='issue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
